# Generated by Django 4.0.4 on 2022-06-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_category',
            name='car_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car_category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car_type'),
        ),
    ]
