# Generated by Django 4.0.4 on 2022-06-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_car_category_car_year_alter_car_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='passager',
            name='district',
        ),
        migrations.RemoveField(
            model_name='city',
            name='addition',
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Passager',
        ),
        migrations.DeleteModel(
            name='Speed',
        ),
    ]
